---
- name: Create new project for DAP and push image
  shell: |
    oc login -u developer
    oc new-project conjur
    docker tag $(docker image ls | grep conjur-appliance | awk '//{print$3}') 172.30.1.1:5000/conjur/conjur-appliance
    docker login -u developer -p $(oc whoami -t) 172.30.1.1:5000
    docker push 172.30.1.1:5000/conjur/conjur-appliance

- name: Grant anyuid privileges to conjur project default service account.
  shell: |
    oc login -u system:admin
    oc adm policy add-scc-to-user anyuid system:serviceaccount:conjur:default

- name: Start conjur
  shell: |
    oc login -u developer
    oc delete project myproject
    oc create -f {{ role_path }}/files/conjurFollower.yml
  args:
    chdir: /opt/openshift

- name: Configure conjur follower certificate
  shell: |
    docker exec {{ conjur_container_name }} evoke ca issue --force {{ okd_fqdn }}
    docker exec {{ conjur_container_name }} evoke ca issue --force {{ okd_follower_service }}
    docker exec {{ conjur_container_name }} chpst -u conjur conjur-plugin-service possum rake authn_k8s:ca_init["conjur/authn-k8s/okd-follower"]
  ignore_errors: true

- name: Create DAP seed file.
  shell: |
    docker exec {{ conjur_container_name }} evoke seed follower {{ okd_follower_service }}  > seed.tar
    oc create configmap seed --from-file seed.tar -o yaml --dry-run | oc replace -f -
    rm -f seed.tar
  args:
    chdir: /opt/openshift/

- name: Get follower pod name
  shell: |
    oc get pods | grep conjur | awk '{print$1}'
  register: podName

- name: Delete current pod
  shell: |
    oc delete pod {{ podName.stdout }}

- pause:
    seconds: 10

- name: Get follower pod name
  shell: |
    oc get pods | grep conjur | awk '{print$1}'
  register: podName

- name: Grab Conjur docker ip
  shell: |
    docker inspect {{ conjur_container_name }} | jq .[].NetworkSettings.IPAddress | tr -d \"
  register: conjur_docker_ip

- name: set hosts file
  shell: |
    oc exec {{ podName.stdout }} -i -t -- bash -c 'echo "{{ conjur_docker_ip.stdout }} {{ conjur_container_name}}" >> /etc/hosts'

- name: Unpack seed
  shell: |
    oc exec {{ podName.stdout }} -- evoke unpack seed /seed/seed.tar

- name: Configure follower
  shell: |
    oc exec {{ podName.stdout }} -- evoke configure follower
