---
- name: Create Roles and Rolebinding
  shell: |
    oc new-project summon-app
    oc login -u system:admin
    oc project summon-app
    oc create -f {{ role_path }}/files/summon-app_security.yml

- name: Get Conjur SSL cert
  shell: |
    docker exec {{ conjur_container_name }} cat /opt/conjur/etc/ssl/conjur-master.pem
  register: conjur_ssl

- name: Create configmap and store ssl cert
  shell: |
    oc login -u developer
    oc project summon-app
    oc create configmap k8s-app-ssl --from-literal=ssl-certificate={{ conjur_ssl.stdout }}
    oc create -f {{ role_path }}/files/summon-app.yml
