---
- name: Start splunk container
  docker_container:
    name: "{{ splunk_container_name }}"
    image: "{{ splunk_image_name }}"
    state: started
    user: root
    recreate: yes
    hostname: "{{ splunk_hostname }}"
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ splunk_external_port}}:{{ splunk_internal_port }}"
     - "{{ splunk_rest_port }}:{{ splunk_rest_port }}"
    volumes:
     - "{{ splunk_audit_volume }}:{{ splunk_audit_directory }}"
    env:
      SPLUNK_START_ARGS="--accept-license --seed-passwd "{{ splunk_account_password }}""
      SPLUNK_USER="root"
      SPLUNK_CMD="add user {{ splunk_account }} -password {{ splunk_account_password }} -role admin -auth admin:{{ splunk_account_password }}"
      SPLUNK_CMD_1="add monitor /conjur/audit.json"
    restart_policy: always

- name: Wait for Splunk to start
  uri:
    url: "http://localhost:8000/en-US/account/login?return_to=%2Fen-US%2F"
    return_content: yes
  register: webpage
  until: '"Splunk Inc" in webpage.content'
  retries: 60
  delay: 3

- name: Create Conjur Dashboard
  uri:
    url: "https://localhost:{{ splunk_rest_port }}/servicesNS/{{ splunk_account }}/search/data/ui/views"
    user: "{{ splunk_account }}"
    password: "{{ splunk_account_password }}"
    status_code: 201
    method: POST
    body: "name=conjur&eai:data={{ lookup('file','files/conjur_dashboard.xml') }}"
    validate_certs: no