---
- name: Remove outdated Docker packages if any
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes
 
