---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure Docker is installed
  yum:
    name: "{{ docker_package }}"
    update_cache: yes
    state: present
  notify: "start docker"
  become: true

- name: ensure docker-python is installed
  pip:
    name: docker
    state: latest
    extra_args: --ignore-installed
  become: true

- name: ensure Docker network is available
  shell: |
    systemctl enable docker
    systemctl start docker
    docker network create test
    docker network rm test
  ignore_errors: yes
  become: true
