- !policy
  id: nodes
  body:
    - !layer

    - !host-factory
      layers: [ !layer ]

    - !permit
      role: !layer /jenkins/nodes
      privileges: 
        - execute
        - read
        - update
      resource: !host-factory
      
    - !permit
      role: !group /admins
      privileges:
        - execute
        - read
        - update
      resource: !host-factory