---
- hosts: toolMachines
  pre_tasks:
    - name: Verify Ansible is greater than 2.5
      assert:
        that: "ansible_version.full is version_compare('2.6', '>=')"
        msg: >
          " You must update Ansible to at least 2.6."
  vars_prompt:
    - name: "okd_domain"
      prompt: "Enter your domain name:"
      default: "cyberarkdemo.local"
  roles:
    - machinePrep
    - conjurConfig
    - weavescopeConfig
    - gogsConfig
    - jenkinsConfig
    - ansibleConfig
    - splunk
    - openshiftConfig
    - kubernetesConfig