---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seed
  namespace: dap
  labels:
    app: dap
data:
  seed.tar: ''

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dap-follower
  namespace: dap
  labels:
    app: dap
spec:
  replicas: 2
  selector:
    matchLabels:
      role: follower
  template:
    metadata:
      labels:
        role: follower
    spec:
      volumes:
      - name: seed
        configMap:
          name: seed
      containers:
      - name: follower
        imagePullPolicy: IfNotPresent
        image: 172.30.1.1:5000/dap/dap-appliance
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/okd-follower
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          - containerPort: 1999
            protocol: TCP
        volumeMounts:
        - mountPath: /seed
          name: seed

---
apiVersion: v1
kind: Service
metadata:
  name: dap-follower
  namespace: dap
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    role: follower
  type: ClusterIP
