---
- name: Create volume for audit data
  docker_volume:
    name: "{{ conjur_audit_volume }}"
    state: present

- name: Load Conjur appliance image from archive
  docker_image:
    name: "{{ conjur_EE_image_name }}"
    load_path: "{{ conjur_tar_path }}"
    state: present
    timeout: 120

- name: Get facts of loaded images
  docker_image_facts:
  register: loaded

- name: Get full name of conjur-appliance image
  set_fact:
    conjur_EE_image_name: "{{ item }}"
  with_items: "{{ loaded.images | json_query('[].RepoTags[0]') }}"
  when: ('conjur-appliance' in item)

- name: Start Conjur appliance
  docker_container:
    name: "{{ conjur_container_name }}"
    image: "{{ conjur_EE_image_name }}"
    state: started
    privileged: yes
    recreate: yes
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ conjur_https_port }}:443"
     - "{{ conjur_postgres_rep_port }}:5432"
    volumes:
     - "{{ conjur_audit_volume }}:{{ conjur_audit_directory }}"
    restart_policy: always

- name: Configure Conjur container
  shell: |
    docker exec {{ conjur_container_name }} \
      evoke configure master \
        -h {{ conjur_container_name }} \
        -p {{ conjur_admin_password }} \
        {{ conjur_account }}

- name: Add Conjur Master's TLS cert to the CLI container
  shell: |
    docker cp -L {{ conjur_container_name }}:/opt/conjur/etc/ssl/conjur.pem \
      {{ role_path }}/files/conjur.pem
    docker cp {{ role_path }}/files/conjur.pem \
      {{ conjur_cli_container_name }}:/root/conjur.pem

- name: Login the CLI container as Conjur admin
  shell: |
    docker exec {{ conjur_cli_container_name }} \
      conjur authn login -u admin -p {{ conjur_admin_password }}

- include_tasks: conjurFramework.yml
