---
- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
   - sudo
   - jq
   - curl
   - git
   - apt-transport-https
   - ca-certificates
   - gnupg2
   - software-properties-common
   - python-apt

- name: Install PIP
  easy_install:
    name: pip
    state: latest

- name: install Ansible Dependencies
  pip:
    name: " {{ item }}"
    state: latest
  with_items:
    - virtualenv
    - python-apt

- name: Remove outdated Docker packages if any
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add docker repo
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes