---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: openshiftPrep.yml
  when: openshift_install == 'YES'

- name: ensure Docker is installed
  yum:
    name: docker
    update_cache: yes
    state: present

- name: start and enable docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- name: ensure docker-python is installed
  pip:
    name: docker
    state: latest
    extra_args: --ignore-installed

- name: Set SELINUX to permissive mode
  selinux:
    policy: targeted
    state: permissive
