---
- name: Check for conjur.tar
  stat:
    path: ../conjur.{{item}}
  with_items:
    - "tar"
    - "tar.gz"
    - "tgz"
  register: conjurTar

- name: Inform about Enterprise availability
  set_fact:
    conjur_version: 'EE'
    conjur_tar_path: "{{ item.stat.path }}"
  when: item.stat.exists
  with_items: "{{ conjurTar.results }}"

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure Docker is installed
  yum:
    name: "{{ docker_package }}"
    update_cache: yes
    state: present
  notify: "start docker"

- name: ensure docker-python is installed
  pip:
    name: docker
    state: latest
    extra_args: --ignore-installed

- name: ensure Docker network is available
  shell: |
    systemctl enable docker
    systemctl start docker
    docker network create test
    docker network rm test
  ignore_errors: yes