- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: openshiftPrep.yml
  when: openshift_install == 'YES'

- name: Ensure Docker is started
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Set insecure registry for openshift
  lineinfile:
    path: /etc/docker/daemon.json
    state: present
    insertafter: EOF
    line: '{"insecure-registries":["172.30.0.0/16"]}'
    create: yes
  when: openshift_install == 'YES'


- name: ensure docker-python is installed
  pip:
    name: docker
    state: latest
    extra_args: --ignore-installed


- name: set up host file to allow for host communication with OKD
  lineinfile:
    path: /etc/hosts
    state: present
    insertafter: EOF
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items:
  - { ip: "{{ ansible_default_ipv4.address }}", hostname: "cdemo-ansible"}
  - { ip: "{{ ansible_default_ipv4.address }}", hostname: "conjur-master"}
  when: openshift_install == 'YES'

- name: Set SELINUX to permissive mode
  selinux:
    policy: targeted
    state: permissive
