---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure Docker is installed
  yum:
    name: docker
    update_cache: yes
    state: present

- name: start and enable docker service
  service:
    name: docker
    state: restarted
    enabled: yes

- name: ensure docker-python is installed
  pip:
    name: docker
    state: latest
    extra_args: --ignore-installed


- name: set up host file to allow for host communication with Conjur
  lineinfile:
    path: /etc/hosts
    state: present
    insertafter: EOF
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items:
  - { ip: "{{ ansible_default_ipv4.address }}", hostname: "cdemo-ansible"}
  - { ip: "{{ ansible_default_ipv4.address }}", hostname: "conjur-master"}
  - { ip: "{{ ansible_default_ipv4.address }}", hostname: "okd"}