---
- name: delete daemon.json
  file:
    state: absent
    path: /etc/docker/daemon.json

- name: Set insecure registry for openshift
  lineinfile:
    path: /etc/docker/daemon.json
    state: present
    insertafter: EOF
    line: '{"insecure-registries":["172.30.0.0/16"]}'
    create: yes
