---
- name: Stop docker service
  service:
    name: docker
    state: stopped
    enabled: yes

- name: delete daemon.json
  file:
    state: absent
    path: /etc/docker/daemon.json

- name: Set insecure registry for openshift
  lineinfile:
    path: /etc/docker/daemon.json
    state: present
    insertafter: EOF
    line: '{"insecure-registries":["172.30.0.0/16"]}'
    create: yes

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: set up host file to allow for host communication with OKD
  lineinfile:
    path: /etc/hosts
    state: present
    insertafter: EOF
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items:
  - { ip: "{{ ansible_default_ipv4.address }}", hostname: "cdemo-ansible"}
  - { ip: "{{ ansible_default_ipv4.address }}", hostname: "conjur-master"}
