---
- name: installDependencies
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - curl
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - git
    - make
    - jq

- name: install PIP
  easy_install:
    name: pip
    state: latest