---
- name: installDependencies
  package:
    name:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
      - make
      - jq
      - docker-ce
      - firewalld
    update_cache: no
    state: latest

- name: install PIP
  easy_install:
    name: pip
    state: latest

- name: start firewalld service
  service:
    name: firewalld
    state: started
