---
- name: Install dependencies
  yum:
    name:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
      - make
      - jq
    state: present
  become: true

- name: install PIP
  easy_install:
    name: pip
    state: latest
  become: true
