---
- name: installDependencies
  yum:
    name:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
      - make
      - jq
    update_cache: yes
    state: latest

- name: install PIP
  easy_install:
    name: pip
    state: latest
