---
- name: installDependencies
  yum:
    name:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
      - make
      - jq
    update_cache: yes
    state: latest

- name: install PIP
  easy_install:
    name: pip
    state: latest

- name: remove outdated Docker packages if any
  yum:
    name:
      - docker
      - docker.io
      - docker-common
      - docker-engine
    state: absent

- name: add docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: /etc/yum.repos.d/docker-{{ docker_edition }}.repo
    owner: root
    group: root
  become: true