---
- name: Ensure epel repository is available
  yum:
    name:
      - epel-release
    state: latest

- name: Set up the Docker package repository
  block:
    - name: Install yum dependencies
      package:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
    - name: Add Docker CE repository to Yum
      shell: |
        yum-config-manager --add-repo \
          https://download.docker.com/linux/centos/docker-ce.repo
  become: true

- name: Ensure installation dependencies are present
  package:
    name:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - git
      - make
      - jq
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - firewalld
    update_cache: yes
    state: latest
  become: true

- name: Ensure Pip is present
  easy_install:
    name: pip
    state: latest
  become: true
