---
- name: Download and extract ansible
  unarchive:
    src: "{{ ansible_download_url }}"
    dest: "/opt"
    remote_src: yes

- name: Configure Ansible Tower
  shell: |
    sed -i "s,admin_password=,admin_password={{ ansible_password }},g" ./inventory
    sed -i "s,pg_password=,pg_password={{ ansible_password }},g" ./inventory
    sed -i "s,rabbitmq_password,rabbitmq_password={{ ansible_password }},g" ./inventory
    sh setup.sh -e nginx_https_port={{ ansible_port }}
  args:
    chdir: "/opt/{{ ansible_download_directory }}"