---
- name: Download and extract ansible
  unarchive:
    src: "{{ ansible_download_url }}"
    dest: "/opt"
    remote_src: yes

- name: Configure Ansible Tower
  shell: |
    sed -i "s,admin_password='',admin_password={{ ansible_password }},g" ./inventory
    sed -i "s,pg_password='',pg_password={{ ansible_password }},g" ./inventory
    sed -i "s,rabbitmq_password='',rabbitmq_password={{ ansible_password }},g" ./inventory
    sh setup.sh -e nginx_https_port={{ ansible_port }}
  args:
    chdir: "/opt/{{ ansible_download_directory }}"

- name: Wait for Ansible tower web interface
  pause:
    seconds: 15
  
- name: Set license
  uri:
    url: "{{ ansible_external_url }}/api/v2/config/"
    method: POST
    validate_certs: NO
    body_format: json
    user: "admin"
    password: "{{ ansible_password }}"
    force_basic_auth: yes
    body: "{{ lookup('file','license.json') }}"